### ISSUE TITLE
the stl file model is deformed in z-axis

### ISSUE THREAD

**Issue by kmordhwaj** [amine0110/nifti-to-stl#2]
Hi @amine0110 , First of all thank you so much for this great script. I am successfully converting the .nii file to .stl file. But the stl file model when opening in blender is deformed one. It is shrinked across z-axis (longest axis). Can you help?

**Comment by amine0110** [comment]
Hi

Actually I don't have other options using numpy-stl!
But VTk provides an excellent module to do the same operation, you can check it out :)
